"""Keep one completed C/D recovery point after its exact first-epoch CPU audit."""
import argparse
import hashlib
import json
import os
import stat
import time
from datetime import datetime, timezone
from pathlib import Path

PROJECT = Path(__file__).resolve().parents[1]
RUNS = {'adamw': 'xtrack_fixed_mixed_adamw_s2026', 'task_adaptive_only': 'xtrack_task_stats_only_s2026'}


def sha(path):
    digest = hashlib.sha256()
    with Path(path).open('rb') as stream:
        for block in iter(lambda: stream.read(8 * 1024 * 1024), b''):
            digest.update(block)
    return digest.hexdigest()


def describe(path, root):
    assert path.resolve(strict=True) == path and path.parent == root
    metadata = path.lstat()
    assert stat.S_ISREG(metadata.st_mode) and metadata.st_nlink == 1
    return dict(path=str(path), bytes=metadata.st_size, sha256=sha(path))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--optimizer', choices=list(RUNS), required=True)
    args = parser.parse_args()
    run_id = RUNS[args.optimizer]
    root = Path('/home/gaob/rgbx-full-method') / run_id
    assert root.resolve(strict=True) == root
    audit_path = PROJECT / 'reports' / (run_id + '_epoch1_checkpoint_audit.json')
    audit = json.loads(audit_path.read_text())
    assert audit['status'] == 'PASS_CONTROL_EPOCH1_RECOVERY_CHECKPOINT_NOT_BENCHMARK'
    assert audit['run_id'] == run_id and audit['stage'] == 'epoch1'
    assert audit['epoch'] == 1 and audit['global_step'] == 2500
    assert audit['checkpoint'] == str(root / 'XTrack_ep0001.pth.tar')
    assert sha(root / 'XTrack_ep0001.pth.tar') == audit['checkpoint_sha256']
    output = PROJECT / 'reports' / (run_id + '_checkpoint_retention.json')
    assert not output.exists()
    report = dict(status='ACTIVE_KEEP_ONE_COMPLETED_RECOVERY_CHECKPOINT', run_id=run_id,
                  retention_worker_pid=os.getpid(), poll_seconds=240, handled_completed_epoch=0,
                  started_at=datetime.now(timezone.utc).isoformat(), epoch1_audit_sha256=sha(audit_path),
                  deleted=[], removed_file_bytes=0, script_sha256=sha(__file__),
                  best_by_benchmark='NOT_DETERMINED_NO_FORMAL_SCORES',
                  policy='Delete only older named completed checkpoints in this exact owned formal run. Preserve the latest complete model/optimizer/three-rank RNG recovery point; no alias is generated by C/D.',
                  after_training='Keep terminal checkpoint until all three datasets are scored and compared; best measured method selection happens outside this worker.',
                  public_weights_and_other_runs='Outside cleanup scope and retained.', training_parameters_modified=False)
    output.write_text(json.dumps(report, indent=2) + '\n')
    while True:
        run = json.loads((root / 'run.json').read_text())
        assert run['run_id'] == run_id and run['optimizer_kind'] == args.optimizer and run['output'] == str(root)
        completed = run['completed_epochs']
        if completed > report['handled_completed_epoch']:
            keep = root / ('XTrack_ep%04d.pth.tar' % completed)
            assert Path(run['last_checkpoint']) == keep
            current = describe(keep, root)
            targets = []
            for path in sorted(root.glob('XTrack_ep????.pth.tar')):
                if int(path.name[9:13]) < completed:
                    targets.append(describe(path, root))
            for item in targets:
                Path(item['path']).unlink()
                report['deleted'].append(item)
                report['removed_file_bytes'] += item['bytes']
                output.write_text(json.dumps(report, indent=2) + '\n')
            report.update(handled_completed_epoch=completed, retained_checkpoint=current,
                          observed_at=datetime.now(timezone.utc).isoformat())
            output.write_text(json.dumps(report, indent=2) + '\n')
            print(json.dumps(dict(completed_epoch=completed, retained=current['path'], removed_files=len(targets))), flush=True)
        if run['status'] == 'TRAINING_COMPLETE_REQUIRES_ENDPOINT_AND_RESULT_AUDIT':
            report.update(status='FINAL_CHECKPOINT_RETAINED_AWAITING_COMPLETE_METRICS',
                          ended_at=datetime.now(timezone.utc).isoformat())
            output.write_text(json.dumps(report, indent=2) + '\n')
            break
        time.sleep(240)


if __name__ == '__main__':
    main()
